<a href="https://colab.research.google.com/github/codebysumit/Tutorials/blob/master/2.%20NumPy/phase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
a = np.random.randint(1,100,15)
a

array([ 9, 80, 90, 17,  4, 18, 68, 33,  6, 41, 83, 26, 29, 28, 44])

In [4]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[ 6, 98, 97, 58],
       [78, 63, 65, 14],
       [87, 49, 12, 20],
       [12, 50, 33,  6],
       [30, 77, 47, 44],
       [31, 20, 52,  1]])

In [10]:
np.sort(a)[::-1]

array([90, 83, 80, 68, 44, 41, 33, 29, 28, 26, 18, 17,  9,  6,  4])

In [14]:
# 0 => col and 1 => row
np.sort(b,axis=0)
# np.sort(b,axis=1)

array([[ 6, 20, 12,  1],
       [12, 49, 33,  6],
       [30, 50, 47, 14],
       [31, 63, 52, 20],
       [78, 77, 65, 44],
       [87, 98, 97, 58]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [15]:
# code
np.append(a, 200)

array([  9,  80,  90,  17,   4,  18,  68,  33,   6,  41,  83,  26,  29,
        28,  44, 200])

In [16]:
b

array([[ 6, 98, 97, 58],
       [78, 63, 65, 14],
       [87, 49, 12, 20],
       [12, 50, 33,  6],
       [30, 77, 47, 44],
       [31, 20, 52,  1]])

In [47]:
arr = np.random.random((b.shape[0],1))
arr

array([[0.70252891],
       [0.55954798],
       [0.44308537],
       [0.38782267],
       [0.36460211],
       [0.42565963]])

In [51]:
np.append(b, arr, axis=1)

array([[ 6.        , 98.        , 97.        , 58.        ,  0.70252891],
       [78.        , 63.        , 65.        , 14.        ,  0.55954798],
       [87.        , 49.        , 12.        , 20.        ,  0.44308537],
       [12.        , 50.        , 33.        ,  6.        ,  0.38782267],
       [30.        , 77.        , 47.        , 44.        ,  0.36460211],
       [31.        , 20.        , 52.        ,  1.        ,  0.42565963]])

In [58]:
arr = np.random.random((1, b.shape[1]))
arr

array([[0.68375813, 0.85974579, 0.90853653, 0.26027251]])

In [59]:
np.append(b, arr, axis=0)

array([[ 6.        , 98.        , 97.        , 58.        ],
       [78.        , 63.        , 65.        , 14.        ],
       [87.        , 49.        , 12.        , 20.        ],
       [12.        , 50.        , 33.        ,  6.        ],
       [30.        , 77.        , 47.        , 44.        ],
       [31.        , 20.        , 52.        ,  1.        ],
       [ 0.68375813,  0.85974579,  0.90853653,  0.26027251]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [61]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c, end="\n\n")
print(d, end="\n\n")

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]



In [62]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [72]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [73]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [69]:
a

array([ 9, 80, 90, 17,  4, 18, 68, 33,  6, 41, 83, 26, 29, 28, 44])

In [64]:
# code
a.shape

(15,)

In [70]:
np.expand_dims(a, axis=0)

array([[ 9, 80, 90, 17,  4, 18, 68, 33,  6, 41, 83, 26, 29, 28, 44]])

In [66]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [68]:
np.expand_dims(a, axis=1)

array([[ 9],
       [80],
       [90],
       [17],
       [ 4],
       [18],
       [68],
       [33],
       [ 6],
       [41],
       [83],
       [26],
       [29],
       [28],
       [44]])

In [71]:
np.expand_dims(a, axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [74]:
a

array([ 9, 80, 90, 17,  4, 18, 68, 33,  6, 41, 83, 26, 29, 28, 44])

In [75]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  2,  6, 10]),)

In [76]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 9,  0,  0, 17,  4, 18,  0, 33,  6, 41,  0, 26, 29, 28, 44])

In [77]:
np.where(a%2 == 0,0,a)

array([ 9,  0,  0, 17,  0,  0,  0, 33,  0, 41, 83,  0, 29,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [78]:
a

array([ 9, 80, 90, 17,  4, 18, 68, 33,  6, 41, 83, 26, 29, 28, 44])

In [ ]:
# np.argmin
np.argmin(a)

13

In [79]:
b

array([[ 6, 98, 97, 58],
       [78, 63, 65, 14],
       [87, 49, 12, 20],
       [12, 50, 33,  6],
       [30, 77, 47, 44],
       [31, 20, 52,  1]])

In [83]:
# np.argmin(b,axis=0)
# np.argmin(b,axis=1)

# b.argmin(axis=1)
b.argmin(axis=0)

array([0, 5, 2, 5])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [ ]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.percentile(a,50)

37.0

In [ ]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.flip(b,axis=1)

array([[ 6, 42, 52, 12],
       [55, 47, 18, 29],
       [ 9, 83, 93, 61],
       [85, 44, 63, 38],
       [72, 31, 87,  8],
       [ 7,  2, 71, 40]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [84]:
# code
a

array([ 9, 80, 90, 17,  4, 18, 68, 33,  6, 41, 83, 26, 29, 28, 44])

In [86]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  90,  17,   4,  18,  68,  33,   6,  41,  83,  26,  29,
        28,  44])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [87]:
# code
a

array([110, 530,  90,  17,   4,  18,  68,  33,   6,  41,  83,  26,  29,
        28,  44])

In [88]:
np.delete(a,[0,2,4])

array([530,  17,  18,  68,  33,   6,  41,  83,  26,  29,  28,  44])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [89]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
np.intersect1d(m,n)

array([3, 4, 5])

In [91]:
np.setdiff1d(n,m)

array([6, 7])

In [92]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [94]:
# m[np.in1d(m,1)] # deprecated
m[np.isin(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [95]:
# code
a

array([110, 530,  90,  17,   4,  18,  68,  33,   6,  41,  83,  26,  29,
        28,  44])

In [96]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 75, 25, 25, 25, 68, 33, 25, 41, 75, 26, 29, 28, 44])

### np.swapaxes

numpy.swapaxes(a, axis1, axis2) efficiently interchanges two specified axes of a NumPy array, returning a view rather than a copy for high performance.

https://numpy.org/devdocs/reference/generated/numpy.swapaxes.html

In [98]:
# Example: Swapping axes for a 2D array (rows and columns)
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape (2, 3) -> Swapping axis 0 and 1 -> Shape (3, 2)
swapped = np.swapaxes(arr, 0, 1)

print(arr, "\n")
print(swapped)

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]


### np.random.uniform

`np.random.uniform()` generates random **floating-point** numbers from a uniform distribution within a specified range **[low, high]**, where the lower bound is inclusive and upper is exclusive. It is commonly used for sampling, simulations, and initializing weights in neural networks, allowing for an equal probability of occurrence for all values in the interval.

https://numpy.org/doc/2.1/reference/random/generated/numpy.random.uniform.html

In [99]:
import numpy as np
# Generate a 2x3 array of random numbers between -1 and 1
samples = np.random.uniform(-1.0, 1.0, size=(2, 3))
print(samples)


[[-0.32677897 -0.64561571 -0.89429176]
 [ 0.99071458  0.38409502  0.57124292]]


### numpy.count_nonzero

The `numpy.count_nonzero()` function counts the number of non-zero elements in a given NumPy array. This function is useful for quickly assessing the density of data or counting valid entries in datasets.

https://numpy.org/doc/2.3/reference/generated/numpy.count_nonzero.html


In [101]:
# Create a sample array
x = np.array([[0, 10, 20],
              [20, 30, 40],
              [0, 0, 0]])

# Count total non-zero elements in the entire array
total_nonzero = np.count_nonzero(x)
print(f"Total non-zero elements: {total_nonzero}") # Output: 5

# Count non-zero elements along axis 0 (columns)
nonzero_along_axis0 = np.count_nonzero(x, axis=0)
print(f"Non-zero elements along axis 0 (col): {nonzero_along_axis0}") # Output: [1 2 2]

# Count non-zero elements along axis 1 (rows)
nonzero_along_axis1 = np.count_nonzero(x, axis=1)
print(f"Non-zero elements along axis 1 (row): {nonzero_along_axis1}") # Output: [2 3 0]


Total non-zero elements: 5
Non-zero elements along axis 0 (col): [1 2 2]
Non-zero elements along axis 1 (row): [2 3 0]


### np.tile

**np.tile()** is a NumPy function that constructs a new array by repeating an input array `(A)` a specified number of times `(reps)`, effectively tiling it. It expands dimensions based on reps (e.g., (2, 3) repeats 2 times vertically and 3 times horizontally) and is essential for data broadcasting in machine learning.

https://numpy.org/doc/2.3/reference/generated/numpy.tile.html

In [102]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [103]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [104]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [105]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [106]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### np.repeat

The `numpy.repeat()` function is used to repeat elements of an input array a specified number of times along a given axis. It returns a new array and does not modify the original one.

https://numpy.org/doc/2.3/reference/generated/numpy.repeat.html

In [108]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [109]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)


array([1, 1, 2, 2, 3, 3, 4, 4])

In [110]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [111]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

### np.allclose

**numpy.allclose()**

This function is designed to handle the inherent precision limitations of floating-point arithmetic. It returns True if two arrays are element-wise equal within a combination of relative and absolute tolerances.

https://numpy.org/doc/2.1/reference/generated/numpy.allclose.html

In [112]:
np.allclose([1e10,1e-7], [1.00001e10,1e-8])

False

In [113]:
np.allclose([1e10,1e-8], [1.00001e10,1e-9])

True

In [114]:
np.allclose([1e10,1e-8], [1.0001e10,1e-9])

False

In [115]:
np.allclose([1.0, np.nan], [1.0, np.nan])

False

In [116]:
np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)

True

### np.equals

**np.equal** is a NumPy universal function (ufunc) that performs an element-wise comparison of two arrays, returning a boolean array (True where elements match, False otherwise). It supports broadcasting, allowing comparisons between arrays of different shapes or with scalars.

https://numpy.org/doc/stable/reference/generated/numpy.equal.html

In [123]:
np.equal([0, 1, 3], np.arange(3))

array([ True,  True, False])

In [124]:
np.equal(1, np.ones(1))

array([ True])

In [125]:
a = np.array([2, 4, 6])
b = np.array([2, 4, 2])
a == b

array([ True,  True, False])

# Some Good Resource

- https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

- https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5
